name: Docker Image Builder

on:
  workflow_dispatch:
      inputs:
        branch_select:
          description: 'Branch to build from'
          required: true
          default: 'master' 
          type: choice
          options:
          - master
          
        image_select:
          description: 'Docker image to build'
          required: true
          default: 'base' 
          type: choice
          options:
          - base
          
jobs:

  build:
  
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Install the pre-requisites
        run:  sudo apt-get update && sudo apt-get install apt-cacher-ng

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Checkout repository
        uses: actions/checkout@v3
          ref: ${{ github.event.inputs.branch_select }}
    
      - name: Build the Docker image
        run: |
          cd ${{ github.event.inputs.image_select }} && \
          docker build -t ${{ github.event.inputs.image_select }} . \
          --build-arg CACHE_DATE:$(date +%Y-%m-%d) \
          --add-host=aptcacher.internal:host-gateway

      - name: Tag Docker image
        run: |
          docker tag debian_buildenv ghcr.io/andrewharle/Docker/${{ github.event.inputs.image_select }}:$(date +%Y%m%d) && \
          docker tag debian_buildenv ghcr.io/andrewharle/Docker/${{ github.event.inputs.image_select }}:latest
        
      - name: Push Docker image
        run: |
          docker push ghcr.io/andrewharle/Docker/${{ github.event.inputs.image_select }}:$(date +%Y%m%d) && \
          docker push ghcr.io/andrewharle/Docker/${{ github.event.inputs.image_select }}:latest
